Repository demaceo/whats-cookin, pull requests merged in 2020-10, with the labels that each got.

#2 Feature classes
  data/ingredients.js
  data/recipes.js
  data/users.js
  src/pantry.js
  src/recipe.js
  src/user.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: enhancement

#3 Add testing and methods for Pantry class, change to other data files …
  data/easy-recipe.js
  data/ingredients.js
  data/recipes.js
  src/pantry.js
  test/pantry-test.js
Labels: enhancement

#4 Add User class and related tests
  src/user.js
  test/user-test.js
Labels: enhancement

#6 Feature/homepage
  src/index.html
  src/styles.css
Labels: enhancement

#9 Feature/html css
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#10 Feature/dom setup
  assets/minus.svg
  assets/plus.svg
  assets/users-solid.svg
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#11 DOM interactions, Styling additions, Class definitions
  assets/Monster-Mash-Cookies.jpg
  assets/ghost-cookies.jpg
  assets/prolapsed-cake.jpg
  assets/pumpkincheesecake.png
  assets/raspberry-souffle.jpg
  assets/spider-cake.jpg
  assets/spookycupcakes.webp
  assets/times-solid.svg
  data/recipes.js
  data/users.js
  src/index.html
  src/pantry.js
  src/recipe.js
  src/scripts.js
  src/styles.css
  src/user.js
Labels: enhancement

#12 Features and Refinements
  assets/Untitled.svg
  assets/board.jpg
  assets/bookmark-gray.svg
  assets/bookmark-hover-red.svg
  assets/bookmark-solid-red.svg
  assets/cart-empty.svg
  assets/cart-full.svg
  assets/cookie-bite.svg
  assets/cookie-color.svg
  assets/dollar-color.svg
  assets/dollar-color2.svg
  assets/ingredients-have.svg
  assets/ingredients-missing.svg
  assets/meclimb.jpg
  assets/star-empty.svg
  assets/star-filled-color.svg
  data/ingredients.js
  data/recipes.js
  data/users.js
  src/index.html
  src/scripts.js
  src/styles.css
  src/user.js
Labels: enhancement

#13 Feature/user section
  assets/bookmark-light.svg
  src/index.html
  src/recipe.js
  src/scripts.js
  src/styles.css
  src/user.js
Labels: enhancement

#14 Feature/user section
  data/recipes.js
  data/users.js
  src/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement

#15 Eslint/refactor
  .eslintrc.js
  data/recipes.js
  package-lock.json
  package.json
  src/index.html
  src/pantry.js
  src/recipe.js
  src/scripts.js
  src/styles.css
  src/user.js
Labels: enhancement

#17 Fix bug in CSS and remove commented code
  src/styles.css
Labels: bug

#18 Feature/user section
  index.html
  src/scripts.js
  src/user.js
Labels: enhancement

#19 Add one line change to show filter esults. Add fix to reflect bookmar…
  index.html
  src/scripts.js
Labels: enhancement

#21 Bug fix: recipe view not working w/o user login
  src/scripts.js
Labels: bug, enhancement

#22 Fix bug could not favorite recipe from recipe view when signed in
  index.html
  src/scripts.js
Labels: bug
